Imported Upstream version 2.5.6

diff --git a/sources/core/tools/oarnodecheck/oarnodecheckquery.in b/sources/core/tools/oarnodecheck/oarnodecheckquery.in
--- a/sources/core/tools/oarnodecheck/oarnodecheckquery.in
+++ b/sources/core/tools/oarnodecheck/oarnodecheckquery.in
@@ -1,25 +1,23 @@
 #!/bin/bash
-# $id$
 
-OARUSER=%%OAROWNER%%
-eval CHECKLOGDIR=~$OARUSER/checklogs
+CHECKLOGDIR=%%OARHOMEDIR%%/checklogs
 CHECKSCRIPTDIR=%%OARCONFDIR%%/check.d
 OARNODECHECKRUN=%%OARDIR%%/oarnodecheckrun
 OARDODO=%%OARDIR%%/oardodo/oardodo
-STAMPFILE=$CHECKSCRIPTDIR/oarnodecheckrun.lastrun
+STAMPFILE=%%OARHOMEDIR%%/oarnodecheckrun.lastrun
 DELAY=3600 # seconds
 
 shopt -s nullglob
 
-if [ -f $STAMPFILE ]; then
-  if [ $(expr `date +"%s"` - `stat --printf="%Y" $STAMPFILE`) -ge $DELAY  ]; then
-    SUDO=""
-    # User $OARUSER MUST be sudoer !
-    [ "$UID" -eq 0 ] || SUDO="$OARDODO"
-    $SUDO $OARNODECHECKRUN || exit 1
-  fi
+# Run oarnodecheck if not run before or if last run is older then DELAY
+if ! [ -f $STAMPFILE ] || [ $(($(date +"%s") - $(stat --printf="%Y" $STAMPFILE))) -ge $DELAY  ]; then
+  SUDO=""
+  # Run as root
+  [ "$UID" -eq 0 ] || SUDO="$OARDODO"
+  $SUDO $OARNODECHECKRUN || exit 1
 fi
 
+# If any log file exists, check failed
 for f in $CHECKLOGDIR/*; do
 	exit 2
 done
