oarsh_shell with systemd, backport ciment, WIP

diff --git a/sources/core/tools/oarsh/oarsh_shell.in b/sources/core/tools/oarsh/oarsh_shell.in
--- a/sources/core/tools/oarsh/oarsh_shell.in
+++ b/sources/core/tools/oarsh/oarsh_shell.in
@@ -24,129 +24,166 @@ OLDUMASK=$(umask)
 umask 0022
 shopt -s nullglob
 
+# Check if we are using systemd
+if [ -f /etc/oar/use_systemd ]
+then
+  SYSTEMD=1
+  # "-" are replaced by "_" as systemd interprets them as "/"
+  OAR_CPUSET=${OAR_CPUSET/-/_}
+  OAR_CPUSET=${OAR_CPUSET/./_}
+else
+  SYSTEMD=0
+fi
+
 # $1 = Name of the cpuset
 # $2,$3,... = PIDs to add
 # Add PIDS into the job cgroups
 function add_process_to_cpuset() {
     [ "$1" = "undef" ] && return
-    CPUSETNAME=$1
-    if [ ! -w /dev/cpuset/$CPUSETNAME/tasks ]; then
-        echo "oarsh: Cannot find cpuset file /dev/cpuset/$CPUSETNAME/tasks" 1>&2
-        exit 61
-    fi
-    shift
+    if [ "$SYSTEMD" = "1" ]; then
+        echo "oarsh: Using systemd" 1>&2
+        SLICE=${1##*/}.slice
+        SERVICE=${1##*/}.service
+        # Cgroup check
+        if [ -f "/sys/fs/cgroup/$SLICE/$SERVICE/cgroup.procs" ]; then
+            # Cgroup v2 procsfile found
+            PROCS_FILE="/sys/fs/cgroup/$SLICE/$SERVICE/cgroup.procs"
+        else
+            # We are probably using cgroup v1
+            PROCS_FILE="/sys/fs/cgroup/systemd/$SLICE/cgroup.procs"
+        fi
+        if [ ! -f $PROCS_FILE ]; then
+            echo "oarsh: Cannot find cpuset file : $PROCS_FILE" 1>&2
+            exit 61
+        fi
+        shift
 
-    # Add all processes to the OAR job cgroups
-    for p in $@; do
-        if [ -r $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/tasks ]; then
-            # If the user gave OAR_USER_CPUSET, a sub cpuset cgroup has to be created and configured. If not, just use the one created by the job resources manager.
-            if [ -n "$OAR_USER_CPUSET" ]; then
-                if [[ "$OAR_USER_CPUSET" == +([[:digit:],]) ]]; then
-                    # Rewrite OAR_USER_CPUSET to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
-                    if [ "${COMPUTE_THREAD_SIBLINGS,,}" == "yes" ]; then
-                        # If COMPUTE_THREAD_SIBLINGS="yes" in oar.conf, that means that the OAR DB has not info about the hyper thread siblings, so we have compute it here.
-                        # See the job_resource_manager_cgroup.pl script for more details on that matter.
-                        OAR_USER_CPUSET=$(
-                            for i in ${OAR_USER_CPUSET//,/ }; do
-                                cat /sys/devices/system/cpu/cpu$i/topology/thread_siblings_list
-                            done |  sort -un | paste -sd, -
-                        )
+        # Add each processes to the right OAR cgroups
+        for p in $@; do
+            $OARDIR/oardodo/oardodo sh -c "echo $p > $PROCS_FILE" || return 1
+        done
+
+    # Legacy cgroup v1 support, without systemd
+    else
+        CPUSETNAME=$1
+        if [ ! -w /dev/cpuset/$CPUSETNAME/tasks ]; then
+            echo "oarsh: Cannot find cpuset file /dev/cpuset/$CPUSETNAME/tasks" 1>&2
+            exit 61
+        fi
+        shift
+
+        # Add all processes to the OAR job cgroups
+        for p in $@; do
+            if [ -r $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/tasks ]; then
+                # If the user gave OAR_USER_CPUSET, a sub cpuset cgroup has to be created and configured. If not, just use the one created by the job resources manager.
+                if [ -n "$OAR_USER_CPUSET" ]; then
+                    if [[ "$OAR_USER_CPUSET" == +([[:digit:],]) ]]; then
+                        # Rewrite OAR_USER_CPUSET to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
+                        if [ "${COMPUTE_THREAD_SIBLINGS,,}" == "yes" ]; then
+                            # If COMPUTE_THREAD_SIBLINGS="yes" in oar.conf, that means that the OAR DB has not info about the hyper thread siblings, so we have compute it here.
+                            # See the job_resource_manager_cgroup.pl script for more details on that matter.
+                            OAR_USER_CPUSET=$(
+                                for i in ${OAR_USER_CPUSET//,/ }; do
+                                    cat /sys/devices/system/cpu/cpu$i/topology/thread_siblings_list
+                                done |  sort -un | paste -sd, -
+                            )
+                        else
+                            OAR_USER_CPUSET=$(echo ${OAR_USER_CPUSET//,/ } | xargs -n1 | sort -un | paste -sd, -)
+                        fi
+                        if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET" && \
+                           $OARDIR/oardodo/oardodo sh -c "echo $OAR_USER_CPUSET > $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET/cpuset.cpus" && \
+                           $OARDIR/oardodo/oardodo sh -c "cat $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/cpuset.mems > $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET/cpuset.mems"
+                        then
+                            : # Everthing went fine
+                        else
+                            # It mostly failed because the OAR_USER_CPUSET is not a subset of the job's cpuset
+                            # We do not want OAR to fail and the resource to become suspected here
+                            echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
+                            # Fallback to no OAR_USER_CPUSET defined
+                            OAR_USER_CPUSET=""
+                        fi
                     else
-                        OAR_USER_CPUSET=$(echo ${OAR_USER_CPUSET//,/ } | xargs -n1 | sort -un | paste -sd, -)
-                    fi
-                    if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET" && \
-                       $OARDIR/oardodo/oardodo sh -c "echo $OAR_USER_CPUSET > $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET/cpuset.cpus" && \
-                       $OARDIR/oardodo/oardodo sh -c "cat $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/cpuset.mems > $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET/cpuset.mems"
-                    then
-                        : # Everthing went fine
-                    else
-                        # It mostly failed because the OAR_USER_CPUSET is not a subset of the job's cpuset
-                        # We do not want OAR to fail and the resource to become suspected here
+                        # OAR_USER_CPUSET is defined but syntax is incorrect
                         echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
-                        # Fallback to no OAR_USER_CPUSET defined
                         OAR_USER_CPUSET=""
                     fi
-                else
-                    # OAR_USER_CPUSET is defined but syntax is incorrect
-                    echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
-                    OAR_USER_CPUSET=""
                 fi
-            fi
-            # Feed at least cpuset (security)
-            # OAR_USER_CPUSET is mostly undefined:
-            # Only oarsh lets the user define it optionally
-            # It is never defined when OAR shell is called by oarsub
-            # When executing the shell for oarsub, it feeds the job's default cgroup/cpuset tasks
-            $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET/tasks" || return 1
+                # Feed at least cpuset (security)
+                # OAR_USER_CPUSET is mostly undefined:
+                # Only oarsh lets the user define it optionally
+                # It is never defined when OAR shell is called by oarsub
+                # When executing the shell for oarsub, it feeds the job's default cgroup/cpuset tasks
+                $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/cpuset/$CPUSETNAME/$OAR_USER_CPUSET/tasks" || return 1
 
-            if [ -r "$CGROUP_MOUNT_POINT/devices/$CPUSETNAME/tasks" ]; then
-                if [ -n "$OAR_USER_GPUDEVICE" ]; then
-                    # If the user gave OAR_USER_GPUDEVICE, a sub device cgroup has to be created and configured. If not, just use the one created by the job resources manager.
-                    if [[ "$OAR_USER_GPUDEVICE" == +([[:digit:],]) ]]; then
-                        # Rewrite OAR_USER_GPUDEVICE to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
-                        OAR_USER_GPUDEVICE=$(echo ${OAR_USER_GPUDEVICE//,/ } | xargs -n1 | sort -un | paste -sd, -)
-                        if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE"; then
-                            # deny any nvidia device which is not requested in $OAR_USER_GPUDEVICE
-                            for d in /dev/nvidia{,[1-9]}[0-9]; do
-                                if [[ ",$OAR_USER_GPUDEVICE," == !(*,${d#/dev/nvidia},*) ]]; then
-                                    if $OARDIR/oardodo/oardodo sh -c "echo c 195:${d#/dev/nvidia} rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
-                                        : # Everthing went fine
-                                    else
-                                        # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
-                                        # We do not want OAR to fail and the resource to become suspected here
-                                        echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                                        # Fallback to no OAR_USER_GPUDEVICE defined
-                                        OAR_USER_GPUDEVICE=""
-                                        break
+                if [ -r "$CGROUP_MOUNT_POINT/devices/$CPUSETNAME/tasks" ]; then
+                    if [ -n "$OAR_USER_GPUDEVICE" ]; then
+                        # If the user gave OAR_USER_GPUDEVICE, a sub device cgroup has to be created and configured. If not, just use the one created by the job resources manager.
+                        if [[ "$OAR_USER_GPUDEVICE" == +([[:digit:],]) ]]; then
+                            # Rewrite OAR_USER_GPUDEVICE to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
+                            OAR_USER_GPUDEVICE=$(echo ${OAR_USER_GPUDEVICE//,/ } | xargs -n1 | sort -un | paste -sd, -)
+                            if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE"; then
+                                # deny any nvidia device which is not requested in $OAR_USER_GPUDEVICE
+                                for d in /dev/nvidia{,[1-9]}[0-9]; do
+                                    if [[ ",$OAR_USER_GPUDEVICE," == !(*,${d#/dev/nvidia},*) ]]; then
+                                        if $OARDIR/oardodo/oardodo sh -c "echo c 195:${d#/dev/nvidia} rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
+                                            : # Everthing went fine
+                                        else
+                                            # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
+                                            # We do not want OAR to fail and the resource to become suspected here
+                                            echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
+                                            # Fallback to no OAR_USER_GPUDEVICE defined
+                                            OAR_USER_GPUDEVICE=""
+                                            break
+                                        fi
                                     fi
-                                fi
-                            done
-                            # deny any AMD device which is not requested in $OAR_USER_GPUDEVICE
-                            for d in /dev/dri/renderD1[2-9}][0-9]; do
-                                r=${d#/dev/dri/renderD}
-                                c=$((r - 128))
-                                if [[ ",$OAR_USER_GPUDEVICE," == !(*,$c,*) ]]; then
-                                    if $OARDIR/oardodo/oardodo sh -c "echo c 226:$c rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny" && \
-                                       $OARDIR/oardodo/oardodo sh -c "echo c 226:$r rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
-                                        : # Everthing went fine
-                                    else
-                                        # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
-                                        # We do not want OAR to fail and the resource to become suspected here
-                                        echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                                        # Fallback to no OAR_USER_GPUDEVICE defined
-                                        OAR_USER_GPUDEVICE=""
-                                        break
+                                done
+                                # deny any AMD device which is not requested in $OAR_USER_GPUDEVICE
+                                for d in /dev/dri/renderD1[2-9}][0-9]; do
+                                    r=${d#/dev/dri/renderD}
+                                    c=$((r - 128))
+                                    if [[ ",$OAR_USER_GPUDEVICE," == !(*,$c,*) ]]; then
+                                        if $OARDIR/oardodo/oardodo sh -c "echo c 226:$c rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny" && \
+                                           $OARDIR/oardodo/oardodo sh -c "echo c 226:$r rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
+                                            : # Everthing went fine
+                                        else
+                                            # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
+                                            # We do not want OAR to fail and the resource to become suspected here
+                                            echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
+                                            # Fallback to no OAR_USER_GPUDEVICE defined
+                                            OAR_USER_GPUDEVICE=""
+                                            break
+                                        fi
                                     fi
-                                fi
-                            done
+                                done
+                            else
+                                # Should not fail here (only a mkdir) but we do not want OAR to fail and the resource to become suspected here
+                                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
+                                # Fallback to no OAR_USER_GPUDEVICE defined
+                                OAR_USER_GPUDEVICE=""
+                            fi
                         else
-                            # Should not fail here (only a mkdir) but we do not want OAR to fail and the resource to become suspected here
+                            # OAR_USER_GPUDEVICE is defined but syntax is incorrect
                             echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
                             # Fallback to no OAR_USER_GPUDEVICE defined
                             OAR_USER_GPUDEVICE=""
                         fi
-                    else
-                        # OAR_USER_GPUDEVICE is defined but syntax is incorrect
-                        echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                        # Fallback to no OAR_USER_GPUDEVICE defined
-                        OAR_USER_GPUDEVICE=""
                     fi
-                fi
-                # Only oarsh lets the user define OAR_USER_GPUDEVICE, optionally. It is never defined when OAR shell is called by oarsub.
-                # When executing the shell for oarsub, the job's default devices cgroup tasks is feeded:
-                # OAR_USER_GPUDEVICE is undefined and ".../$OAR_USER_GPUDEVICE/tasks" becomes "...//tasks", with a harmless double "/".
-                $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/tasks" || return 1
-            fi 
-            for c in $CGROUP_MOUNT_POINT/*; do
-                if [ "$c" != "$CGROUP_MOUNT_POINT/cpuset" -a "$c" != "$CGROUP_MOUNT_POINT/devices" -a -r "$c/$CPUSETNAME/tasks" ]; then
-                    $OARDIR/oardodo/oardodo sh -c "echo $p > $c/$CPUSETNAME/tasks" || return 1
-                fi
-            done
-        else
-            # Old behaviour without cgroups (just cpuset)
-            $OARDIR/oardodo/oardodo sh -c "echo $p > /dev/cpuset/$CPUSETNAME/tasks" || return 1
-        fi
-    done
+                    # Only oarsh lets the user define OAR_USER_GPUDEVICE, optionally. It is never defined when OAR shell is called by oarsub.
+                    # When executing the shell for oarsub, the job's default devices cgroup tasks is feeded:
+                    # OAR_USER_GPUDEVICE is undefined and ".../$OAR_USER_GPUDEVICE/tasks" becomes "...//tasks", with a harmless double "/".
+                    $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/tasks" || return 1
+                fi 
+                for c in $CGROUP_MOUNT_POINT/*; do
+                    if [ "$c" != "$CGROUP_MOUNT_POINT/cpuset" -a "$c" != "$CGROUP_MOUNT_POINT/devices" -a -r "$c/$CPUSETNAME/tasks" ]; then
+                        $OARDIR/oardodo/oardodo sh -c "echo $p > $c/$CPUSETNAME/tasks" || return 1
+                    fi
+                done
+            else
+                # Old behaviour without cgroups (just cpuset)
+                $OARDIR/oardodo/oardodo sh -c "echo $p > /dev/cpuset/$CPUSETNAME/tasks" || return 1
+            fi
+        done
+    fi
 }
 
 if [ "$OAR_JOB_USER" = "" ]
