cg device ok

diff --git a/sources/core/tools/oarsh/oarsh_shell.in b/sources/core/tools/oarsh/oarsh_shell.in
--- a/sources/core/tools/oarsh/oarsh_shell.in
+++ b/sources/core/tools/oarsh/oarsh_shell.in
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 # This is the login shell program for the oar user, used by oarsub/oarexec and
 # oarsh It adds its own process in the OAR cgroups (defined by OAR_CPUSET) and
 # runs the shell or the script of the user defined by OAR_JOB_USER.
@@ -9,8 +9,9 @@
 
 set -e
 set -o pipefail
+shopt -s nullglob
+
 DEFAULT_SHELL=/bin/bash
-CGROUP_MOUNT_POINT=$(grep cgroup2 /proc/mounts | cut -d\  -f2)
 XAUTH_LOCATION="%%XAUTHCMDPATH%%"
 OARDIR="%%OARDIR%%"
 OAR_RUNTIME_DIRECTORY="/tmp/oar_runtime"
@@ -21,109 +22,70 @@ export PATH=$OARDIR/oardodo:$PATH
 
 # File generated by job resource manager on all job nodes
 JOBENVFILE="$OAR_RUNTIME_DIRECTORY/${OAR_CPUSET##*/}.env"
-JOB_ID=${OAR_CPUSET##*_}
-JOB_USER=${OAR_CPUSET%_*}
-JOB_USER=${JOB_USER##*/}
-OAR_CG=${OAR_CPUSET#/}
-OAR_CG=${OAR_CG%%/*}
 
 OLDUMASK=$(umask)
 umask 0022
-shopt -s nullglob
 
 # $1 = Name of the cpuset
 # $2,$3,... = PIDs to add
 # Add PIDS into the job cgroups
 add_process_to_cpuset() {
     [ "$1" = "undef" ] && return
+    CGROUP_MOUNT_POINT=$(sed -ne 's/^cgroup2 \([^ ]\+\) .*/\1/p' /proc/mounts)
+    CGROUP_OAR_PATH=$CGROUP_MOUNT_POINT${OAR_CPUSET%/*}.slice
+    JOB_ID=${OAR_CPUSET##*_}
+    JOB_USER=${OAR_CPUSET##*/}
+    JOB_USER=${JOB_USER%_*}
     JOB_USER_ID=$(id -u "$JOB_USER")
-    JOB_CGROUP_DIR=$CGROUP_MOUNT_POINT/oar.slice/oar-u$JOB_USER_ID.slice/oar-u$JOB_USER_ID-j$JOB_ID.slice
-    if [ ! -e "$JOB_CGROUP_DIR/cgroup.procs" ]; then
-        echo "oarsh: Cannot find the job's cgroup.procs file $JOB_CGROUP_DIR/cgroup.procs" 1>&2
+    SYSTEMD_OAR_SLICE=${CGROUP_OAR_PATH##*/}
+    SYSTEMD_USER_SLICE=${SYSTEMD_OAR_SLICE%.slice}-u$JOB_USER_ID.slice
+    SYSTEMD_JOB_SLICE=${SYSTEMD_USER_SLICE%.slice}-j$JOB_ID.slice
+    SYSTEMD_PROC_SCOPE=${SYSTEMD_JOB_SLICE%.slice}-p$RANDOM.scope
+    CGROUP_USER_PATH=$CGROUP_OAR_PATH/$SYSTEMD_USER_SLICE
+    CGROUP_JOB_PATH=$CGROUP_USER_PATH/$SYSTEMD_JOB_SLICE
+
+    if [ ! -e "$CGROUP_JOB_PATH/cgroup.procs" ]; then
+        echo "oarsh: Cannot find the job's cgroup: $CGROUP_JOB_PATH" 1>&2
         exit 61
     fi
     shift
 
     # Add all processes to the OAR job cgroups
     TASK_ID=""
-    if [ -n "$OAR_USER_CPUSET" ]; then
-        SYSTEMD_ALLOWED_CPUS_STR=$(hwloc-calc --cof systemd-dbus-api "$OAR_USER_CPUSET" | sed -e 's/^AllowedCPUs //')
-        if [ -n "$SYSTEMD_ALLOWED_CPUS_STR" ]; then
-            TASK_ID="-t$RANDOM"
-            oardodo busctl call -q org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartUnit ss $OAR_CG-u$JOB_USER_ID-j$JOB_ID$TASK_ID.slice fail
-            while oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListJobs | grep -q "$OAR_CG-u$JOB_USER_ID-j$JOB_ID$TASK_ID"; do
-                sleep 1
-            done
-            oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager SetUnitProperties 'sba(sv)' $OAR_CG-u$JOB_USER_ID-j$JOB_ID$TASK_ID.slice 1 1 AllowedCPUs $SYSTEMD_ALLOWED_CPUS_STR
-        else
-            # OAR_USER_CPUSET is defined but syntax is incorrect
-            echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
-            OAR_USER_CPUSET=""
-        fi
-    fi
-    oardodo busctl call -q org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartTransientUnit 'ssa(sv)a(sa(sv))' oar-u$JOB_USER_ID-j$JOB_ID$TASK_ID-s$RANDOM.scope fail 3 Delegate b 1 PIDs au $# "$@" Slice s oar-u$JOB_USER_ID-j$JOB_ID$TASK_ID.slice 0
-    while oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListJobs | grep -q "$OAR_CG-u$JOB_USER_ID-j$JOB_ID$TASK_ID"; do
-        sleep 1
-    done
-
-    if [ -r "$CGROUP_MOUNT_POINT/devices/$CPUSETNAME/cgroup.procs" ]; then
-        if [ -n "$OAR_USER_GPUDEVICE" ]; then
-            # If the user gave OAR_USER_GPUDEVICE, a sub device cgroup has to be created and configured. If not, just use the one created by the job resources manager.
-            if [[ "$OAR_USER_GPUDEVICE" == +([[:digit:],]) ]]; then
-                # Rewrite OAR_USER_GPUDEVICE to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
-                OAR_USER_GPUDEVICE=$(echo ${OAR_USER_GPUDEVICE//,/ } | xargs -n1 | sort -un | paste -sd, -)
-                if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE"; then
-                    # deny any nvidia device which is not requested in $OAR_USER_GPUDEVICE
-                    for d in /dev/nvidia{,[1-9]}[0-9]; do
-                        if [[ ",$OAR_USER_GPUDEVICE," == !(*,${d#/dev/nvidia},*) ]]; then
-                            if $OARDIR/oardodo/oardodo sh -c "echo c 195:${d#/dev/nvidia} rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
-                                : # Everthing went fine
-                            else
-                                # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
-                                # We do not want OAR to fail and the resource to become suspected here
-                                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                                # Fallback to no OAR_USER_GPUDEVICE defined
-                                OAR_USER_GPUDEVICE=""
-                                break
-                            fi
-                        fi
-                    done
-                    # deny any AMD device which is not requested in $OAR_USER_GPUDEVICE
-                    for d in /dev/dri/renderD1[2-9}][0-9]; do
-                        r=${d#/dev/dri/renderD}
-                        c=$((r - 128))
-                        if [[ ",$OAR_USER_GPUDEVICE," == !(*,$c,*) ]]; then
-                            if $OARDIR/oardodo/oardodo sh -c "echo c 226:$c rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny" && \
-                               $OARDIR/oardodo/oardodo sh -c "echo c 226:$r rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
-                                : # Everthing went fine
-                            else
-                                # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
-                                # We do not want OAR to fail and the resource to become suspected here
-                                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                                # Fallback to no OAR_USER_GPUDEVICE defined
-                                OAR_USER_GPUDEVICE=""
-                                break
-                            fi
-                        fi
-                    done
-                else
-                    # Should not fail here (only a mkdir) but we do not want OAR to fail and the resource to become suspected here
-                    echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                    # Fallback to no OAR_USER_GPUDEVICE defined
-                    OAR_USER_GPUDEVICE=""
-                fi
+    if [ -n "$OAR_USER_CPUSET" ] || [ -n "$OAR_USER_GPUDEVICE" ]; then
+        SYSTEMD_SUBJOB_SLICE=${SYSTEMD_JOB_SLICE%.slice}-t$RANDOM.slice
+        CGROUP_SUBJOB_PATH=$CGROUP_JOB_PATH/$SYSTEMD_SUBJOB_SLICE
+        SYSTEMD_PROC_SCOPE=${SYSTEMD_SUBJOB_SLICE%.slice}-p$RANDOM.scope
+        oardodo busctl call -q org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartUnit ss $SYSTEMD_SUBJOB_SLICE fail
+        while oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListJobs | grep -q "$SYSTEMD_SUBJOB_SLICE"; do
+            sleep 0.1
+        done
+        if [ -n "$OAR_USER_CPUSET" ]; then
+            SYSTEMD_ALLOWED_CPUS_STR=$(hwloc-calc --cof systemd-dbus-api "$OAR_USER_CPUSET" | sed -e 's/^AllowedCPUs //')
+            if [ -n "$SYSTEMD_ALLOWED_CPUS_STR" ]; then
+                oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager SetUnitProperties 'sba(sv)' $SYSTEMD_SUBJOB_SLICE 1 1 AllowedCPUs $SYSTEMD_ALLOWED_CPUS_STR
             else
-                # OAR_USER_GPUDEVICE is defined but syntax is incorrect
-                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                # Fallback to no OAR_USER_GPUDEVICE defined
-                OAR_USER_GPUDEVICE=""
+                # OAR_USER_CPUSET is defined but syntax is incorrect
+                echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
+                OAR_USER_CPUSET=""
             fi
         fi
-        # Only oarsh lets the user define OAR_USER_GPUDEVICE, optionally. It is never defined when OAR shell is called by oarsub.
-        # When executing the shell for oarsub, the job's default devices cgroup cgroup.procs is feeded:
-        # OAR_USER_GPUDEVICE is undefined and ".../$OAR_USER_GPUDEVICE/cgroup.procs" becomes "...//cgroup.procs", with a harmless double "/".
-        $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/cgroup.procs" || return 1
+        if [ -n "$OAR_USER_GPUDEVICE" ]; then
+            OAR_USER_GPUDEVICE=${OAR_USER_GPUDEVICE//+/ }
+            OAR_USER_GPUDEVICE=${OAR_USER_GPUDEVICE//,/ }
+            declare -a DEV_DENY DEV_ALLOW
+            for f in /dev/nvidia[0-9]* /dev/dri/card[0-9]* /dev/dri/renderD[0-9]* /dev/nvidia-caps/*; do
+                if [[ " $OAR_USER_GPUDEVICE " ==  !(* $f *) ]]; then
+                    DEV_DENY+=($f)
+                fi
+            done
+            oardodo /usr/sbin/oarcgdev $CGROUP_SUBJOB_PATH "${DEV_DENY[@]}"
+        fi
     fi
+    oardodo busctl call -q org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartTransientUnit 'ssa(sv)a(sa(sv))' ${SYSTEMD_PROC_SCOPE} fail 3 Delegate b 1 PIDs au $# "$@" Slice s ${SYSTEMD_PROC_SCOPE%-p*}.slice 0
+    while oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListJobs | grep -q "$SYSTEMD_PROC_SCOPE"; do
+        sleep 0.1
+    done
 }
 
 if [ "$OAR_JOB_USER" = "" ]; then
