User UID + remove eval in oarsh

diff --git a/sources/core/tools/oarsh/oarsh.in b/sources/core/tools/oarsh/oarsh.in
--- a/sources/core/tools/oarsh/oarsh.in
+++ b/sources/core/tools/oarsh/oarsh.in
@@ -200,16 +200,19 @@ if [ -r $TMP_JOB_KEY_FILE ]; then
     exit 4
 fi
 
-if [ "$CPUSET_PATH" != "" ]; then
+if [ -n "$CPUSET_PATH" ]; then
     if [ -r /proc/self/cpuset ]; then
+        unset OAR_CPUSET
         if [ -n "$GET_CURRENT_CPUSET_CMD" ]; then
             OAR_CPUSET=$(bash -c "$GET_CURRENT_CPUSET_CMD")
         else
-            # cpuset must be of the form /oar/username_jobid, this trims any possible sub cpuset directory
-            #OAR_CPUSET=$(grep -o -e "^/oar.slice/oar-U[^.].slice/[^/]\+" /proc/self/cpuset)
-            OAR_CPUSET=$(sed -e 's#^/[^/]\+/[^/]\+/\([^-]\+\)-\([^/]\+\)-\([^/]\+\)\.slice/.*$#/\1/\2_\3#' /proc/self/cpuset)
+            # cpuset must be of the form /oar/username_jobid, extract it from the cgroup path, supposedliy
+            # if not sub task: /oar.slice/oar-Uxxx.slice/oar-uXXX-jYYY.slice/oar-uXXX-jYYY-sZZZ.scope
+            # or if sub task:  /oar.slice/oar-Uxxx.slice/oar-uXXX-jYYY.slice/oar-uXXX-jYYY-tZZZ.slice/oar-uXXX-jYYY-tTTT-sZZZ.scope
+            OAR_CPUSET=$(sed -ne "s#.*$CPUSET_PATH.slice/[^/]\+$CPUSET_PATH-u\([[:digit:]]\+\)-j\([[:digit:]]\+\)\.slice/.*#\1_\2#p" /proc/self/cpuset)
+            OAR_CPUSET=$CPUSET_PATH/$(id -un "${OAR_CPUSET%_*}")_${OAR_CPUSET##*_}
         fi
-        if [ "${OAR_CPUSET%/*}" == "$CPUSET_PATH" ] || [ "${OAR_CPUSET%/*}" == "$CPUSET_PATH/" ]; then
+        if [ -n "${OAR_CPUSET##*/}" ]; then
             JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/${OAR_CPUSET##*/}.jobkey"
             if [ -r $JOB_KEY_FILE ]; then
                 umask $OLDUMASK
@@ -234,43 +237,32 @@ if [ -n "$OAR_JOB_ID" ]; then
         echo "oarsh: Invalid job id: $OAR_JOB_ID" 1>&2
         exit 5
     fi
-    if [ ! -x "$OARSH_OARSTAT_CMD" ]; then
-        echo "oarsh: Cannot connect using job id from this host." 1>&2
-        exit 5
-    fi
-    STR=$($OARSH_OARSTAT_CMD -fj $OAR_JOB_ID | \
-            while read l; do
-                if [ "$l" != "" ]; then
-                    if [ "${l##cpuset_name*}" = "" ] ;then
-                        echo "OAR_CPUSET="${l/*cpuset_name = /}
-                    fi
-                fi
-            done)
-
-    eval $STR
-
-    if [ "$OAR_CPUSET" = "" ]; then
-        echo "oarsh: Cannot retrieve the job cpuset name for job id: $OAR_JOB_ID" 1>&2
-        exit 5
-    else
-        if [ "$OAR_CPUSET" != "$OARDO_USER"_"$OAR_JOB_ID" ]; then
-            echo "oarsh: Permission denied, seems like job $OAR_JOB_ID is not yours." 1>&2
+    if [ -n "$CPUSET_PATH" ]; then
+        if [ ! -x "$OARSH_OARSTAT_CMD" ]; then
+            echo "oarsh: Cannot connect using job id from this host." 1>&2
             exit 5
         fi
-    fi
+        OAR_CPUSET=$CPUSET_PATH/$($OARSH_OARSTAT_CMD -fj "$OAR_JOB_ID" | sed -ne 's/^\s*cpuset_name\s*=\s*\(\w\+\).*$/\1/p')
 
+        if [ "$OAR_CPUSET" == "$CPUSET_PATH/" ]; then
+            echo "oarsh: Cannot retrieve the job cpuset name for job id: $OAR_JOB_ID" 1>&2
+            exit 5
+        else
+            if [ "$OAR_CPUSET" != "${CPUSET_PATH}/${OARDO_USER}_${OAR_JOB_ID}" ]; then
+                echo "oarsh: Permission denied, seems like job $OAR_JOB_ID is not yours." 1>&2
+                exit 5
+            fi
+        fi
+    else
+        OAR_CPUSET="undef"
+    fi
     # Check if we must use a tmp user id for this job
     if [ "$OAR_JOB_USER" = "" ]; then
         OAR_JOB_USER=$OARDO_USER
     fi
-    if [ "$CPUSET_PATH" != "" ]; then
-        OAR_CPUSET="$CPUSET_PATH/$OAR_CPUSET"
-    else
-        OAR_CPUSET="undef"
-    fi
     export OAR_JOB_USER
     export OAR_CPUSET
-    umask $OLDUMASK
+    umask "$OLDUMASK"
     exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET OAR_JOB_USER OAR_USER_CPUSET OAR_USER_GPUDEVICE" "${OPT[@]}" $OARSH_HOST -- "$REMOTE_CMD"
     echo "oarsh: Failed to connect using cpuset environment" 1>&2
     exit 5
diff --git a/sources/core/tools/oarsh/oarsh_shell.in b/sources/core/tools/oarsh/oarsh_shell.in
--- a/sources/core/tools/oarsh/oarsh_shell.in
+++ b/sources/core/tools/oarsh/oarsh_shell.in
@@ -15,7 +15,7 @@ OAR_RUNTIME_DIRECTORY="/tmp/oar_runtime"
 
 export PATH=$OARDIR/oardodo:$PATH
 
-source /etc/oar/oar.conf
+. /etc/oar/oar.conf
 
 # File generated by job resource manager on all job nodes
 JOBENVFILE="$OAR_RUNTIME_DIRECTORY/${OAR_CPUSET##*/}.env"
@@ -30,9 +30,10 @@ shopt -s nullglob
 # $1 = Name of the cpuset
 # $2,$3,... = PIDs to add
 # Add PIDS into the job cgroups
-function add_process_to_cpuset() {
+add_process_to_cpuset() {
     [ "$1" = "undef" ] && return
-    JOB_CGROUP_DIR=$CGROUP_MOUNT_POINT/oar.slice/oar-$JOB_USER.slice/oar-$JOB_USER-$JOB_ID.slice
+    JOB_USER_ID=$(id -u "$JOB_USER")
+    JOB_CGROUP_DIR=$CGROUP_MOUNT_POINT/oar.slice/oar-u$JOB_USER_ID.slice/oar-u$JOB_USER_ID-j$JOB_ID.slice
     if [ ! -e "$JOB_CGROUP_DIR/cgroup.procs" ]; then
         echo "oarsh: Cannot find the job's cgroup.procs file $JOB_CGROUP_DIR/cgroup.procs" 1>&2
         exit 61
@@ -40,135 +41,122 @@ function add_process_to_cpuset() {
     shift
 
     # Add all processes to the OAR job cgroups
-    if [ -r "$JOB_CGROUP_DIR/cgroup.procs" ]; then
-        TASK_ID=""
-        if [ -n "$OAR_USER_CPUSET" ]; then
-            SYSTEMD_ALLOWED_CPUS_STR=$(hwloc-calc --cof systemd-dbus-api "$OAR_USER_CPUSET" | sed -e 's/^AllowedCPUs //')
-            if [ -n "$SYSTEMD_ALLOWED_CPUS_STR" ]; then
-                TASK_ID="-T$RANDOM"
-                if oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartUnit ss "oar-$JOB_USER-$JOB_ID$TASK_ID.slice" fail && \
-                oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager SetUnitProperties 'sba(sv)' oar-$JOB_USER-$JOB_ID$TASK_ID.slice 1 1 AllowedCPUs $SYSTEMD_ALLOWED_CPUS_STR
-                then
-                    : # Everthing went fine
-                else
-                    # It mostly failed because the OAR_USER_CPUSET is not a subset of the job's cpuset
-                    # We do not want OAR to fail and the resource to become suspected here
-                    echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
-                    # Fallback to no OAR_USER_CPUSET defined
-                    OAR_USER_CPUSET=""
-                    TASK_ID=""
-                fi
+    TASK_ID=""
+    if [ -n "$OAR_USER_CPUSET" ]; then
+        SYSTEMD_ALLOWED_CPUS_STR=$(hwloc-calc --cof systemd-dbus-api "$OAR_USER_CPUSET" | sed -e 's/^AllowedCPUs //')
+        if [ -n "$SYSTEMD_ALLOWED_CPUS_STR" ]; then
+            TASK_ID="-t$RANDOM"
+            if oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartUnit ss oar-u$JOB_USER_ID-j$JOB_ID$TASK_ID.slice fail && \
+            oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager SetUnitProperties 'sba(sv)' oar-u$JOB_USER_ID-j$JOB_ID$TASK_ID.slice 1 1 AllowedCPUs $SYSTEMD_ALLOWED_CPUS_STR
+            then
+                : # Everthing went fine
             else
-                # OAR_USER_CPUSET is defined but syntax is incorrect
+                # It mostly failed because the OAR_USER_CPUSET is not a subset of the job's cpuset
+                # We do not want OAR to fail and the resource to become suspected here
                 echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
+                # Fallback to no OAR_USER_CPUSET defined
                 OAR_USER_CPUSET=""
+                TASK_ID=""
             fi
+        else
+            # OAR_USER_CPUSET is defined but syntax is incorrect
+            echo "Warning: Failed to set user cpuset as requested by OAR_USER_CPUSET=$OAR_USER_CPUSET, use the default one" 1>&2
+            OAR_USER_CPUSET=""
         fi
-        # Feed at least cpuset (security)
-        # OAR_USER_CPUSET is mostly undefined:
-        # Only oarsh lets the user define it optionally
-        # It is never defined when OAR shell is called by oarsub
-        # When executing the shell for oarsub, it feeds the job's default cgroup cgroup.procs
+    fi
+    # Feed at least cpuset (security)
+    # OAR_USER_CPUSET is mostly undefined:
+    # Only oarsh lets the user define it optionally
+    # It is never defined when OAR shell is called by oarsub
+    # When executing the shell for oarsub, it feeds the job's default cgroup cgroup.procs
 
-        oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartTransientUnit 'ssa(sv)a(sa(sv))' "oar-$JOB_USER-$JOB_ID$TASK_ID-S$RANDOM.scope" fail 3 Delegate b 1 PIDs au $# "$@" Slice s "oar-$JOB_USER-$JOB_ID$TASK_ID.slice" 0 || return 1
+    oardodo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartTransientUnit 'ssa(sv)a(sa(sv))' oar-u$JOB_USER_ID-j$JOB_ID$TASK_ID-s$RANDOM.scope fail 3 Delegate b 1 PIDs au $# "$@" Slice s oar-u$JOB_USER_ID-j$JOB_ID$TASK_ID.slice 0 || return 1
 
-        if [ -r "$CGROUP_MOUNT_POINT/devices/$CPUSETNAME/cgroup.procs" ]; then
-            if [ -n "$OAR_USER_GPUDEVICE" ]; then
-                # If the user gave OAR_USER_GPUDEVICE, a sub device cgroup has to be created and configured. If not, just use the one created by the job resources manager.
-                if [[ "$OAR_USER_GPUDEVICE" == +([[:digit:],]) ]]; then
-                    # Rewrite OAR_USER_GPUDEVICE to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
-                    OAR_USER_GPUDEVICE=$(echo ${OAR_USER_GPUDEVICE//,/ } | xargs -n1 | sort -un | paste -sd, -)
-                    if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE"; then
-                        # deny any nvidia device which is not requested in $OAR_USER_GPUDEVICE
-                        for d in /dev/nvidia{,[1-9]}[0-9]; do
-                            if [[ ",$OAR_USER_GPUDEVICE," == !(*,${d#/dev/nvidia},*) ]]; then
-                                if $OARDIR/oardodo/oardodo sh -c "echo c 195:${d#/dev/nvidia} rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
-                                    : # Everthing went fine
-                                else
-                                    # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
-                                    # We do not want OAR to fail and the resource to become suspected here
-                                    echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                                    # Fallback to no OAR_USER_GPUDEVICE defined
-                                    OAR_USER_GPUDEVICE=""
-                                    break
-                                fi
+    if [ -r "$CGROUP_MOUNT_POINT/devices/$CPUSETNAME/cgroup.procs" ]; then
+        if [ -n "$OAR_USER_GPUDEVICE" ]; then
+            # If the user gave OAR_USER_GPUDEVICE, a sub device cgroup has to be created and configured. If not, just use the one created by the job resources manager.
+            if [[ "$OAR_USER_GPUDEVICE" == +([[:digit:],]) ]]; then
+                # Rewrite OAR_USER_GPUDEVICE to remove any duplicate and sort, so that whatever the combination given, the cgroup name is the same
+                OAR_USER_GPUDEVICE=$(echo ${OAR_USER_GPUDEVICE//,/ } | xargs -n1 | sort -un | paste -sd, -)
+                if $OARDIR/oardodo/oardodo sh -c "mkdir -p $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE"; then
+                    # deny any nvidia device which is not requested in $OAR_USER_GPUDEVICE
+                    for d in /dev/nvidia{,[1-9]}[0-9]; do
+                        if [[ ",$OAR_USER_GPUDEVICE," == !(*,${d#/dev/nvidia},*) ]]; then
+                            if $OARDIR/oardodo/oardodo sh -c "echo c 195:${d#/dev/nvidia} rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
+                                : # Everthing went fine
+                            else
+                                # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
+                                # We do not want OAR to fail and the resource to become suspected here
+                                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
+                                # Fallback to no OAR_USER_GPUDEVICE defined
+                                OAR_USER_GPUDEVICE=""
+                                break
                             fi
-                        done
-                        # deny any AMD device which is not requested in $OAR_USER_GPUDEVICE
-                        for d in /dev/dri/renderD1[2-9}][0-9]; do
-                            r=${d#/dev/dri/renderD}
-                            c=$((r - 128))
-                            if [[ ",$OAR_USER_GPUDEVICE," == !(*,$c,*) ]]; then
-                                if $OARDIR/oardodo/oardodo sh -c "echo c 226:$c rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny" && \
-                                   $OARDIR/oardodo/oardodo sh -c "echo c 226:$r rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
-                                    : # Everthing went fine
-                                else
-                                    # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
-                                    # We do not want OAR to fail and the resource to become suspected here
-                                    echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                                    # Fallback to no OAR_USER_GPUDEVICE defined
-                                    OAR_USER_GPUDEVICE=""
-                                    break
-                                fi
+                        fi
+                    done
+                    # deny any AMD device which is not requested in $OAR_USER_GPUDEVICE
+                    for d in /dev/dri/renderD1[2-9}][0-9]; do
+                        r=${d#/dev/dri/renderD}
+                        c=$((r - 128))
+                        if [[ ",$OAR_USER_GPUDEVICE," == !(*,$c,*) ]]; then
+                            if $OARDIR/oardodo/oardodo sh -c "echo c 226:$c rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny" && \
+                               $OARDIR/oardodo/oardodo sh -c "echo c 226:$r rwm > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/devices.deny"; then
+                                : # Everthing went fine
+                            else
+                                # It mostly failed because the OAR_USER_GPUDEVICE is not a subset of the job's gpudevices
+                                # We do not want OAR to fail and the resource to become suspected here
+                                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
+                                # Fallback to no OAR_USER_GPUDEVICE defined
+                                OAR_USER_GPUDEVICE=""
+                                break
                             fi
-                        done
-                    else
-                        # Should not fail here (only a mkdir) but we do not want OAR to fail and the resource to become suspected here
-                        echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
-                        # Fallback to no OAR_USER_GPUDEVICE defined
-                        OAR_USER_GPUDEVICE=""
-                    fi
+                        fi
+                    done
                 else
-                    # OAR_USER_GPUDEVICE is defined but syntax is incorrect
+                    # Should not fail here (only a mkdir) but we do not want OAR to fail and the resource to become suspected here
                     echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
                     # Fallback to no OAR_USER_GPUDEVICE defined
                     OAR_USER_GPUDEVICE=""
                 fi
+            else
+                # OAR_USER_GPUDEVICE is defined but syntax is incorrect
+                echo "Warning: Failed to set user gpudevice as requested by OAR_USER_GPUDEVICE=$OAR_USER_GPUDEVICE, use the default one" 1>&2
+                # Fallback to no OAR_USER_GPUDEVICE defined
+                OAR_USER_GPUDEVICE=""
             fi
-            # Only oarsh lets the user define OAR_USER_GPUDEVICE, optionally. It is never defined when OAR shell is called by oarsub.
-            # When executing the shell for oarsub, the job's default devices cgroup cgroup.procs is feeded:
-            # OAR_USER_GPUDEVICE is undefined and ".../$OAR_USER_GPUDEVICE/cgroup.procs" becomes "...//cgroup.procs", with a harmless double "/".
-            $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/cgroup.procs" || return 1
         fi
-    else
-        echo "Error: failed to populate job cgroup $JOB_CGROUP_DIR" 1>&2
-	exit 62
+        # Only oarsh lets the user define OAR_USER_GPUDEVICE, optionally. It is never defined when OAR shell is called by oarsub.
+        # When executing the shell for oarsub, the job's default devices cgroup cgroup.procs is feeded:
+        # OAR_USER_GPUDEVICE is undefined and ".../$OAR_USER_GPUDEVICE/cgroup.procs" becomes "...//cgroup.procs", with a harmless double "/".
+        $OARDIR/oardodo/oardodo sh -c "echo $p > $CGROUP_MOUNT_POINT/devices/$CPUSETNAME/$OAR_USER_GPUDEVICE/cgroup.procs" || return 1
     fi
 }
 
-if [ "$OAR_JOB_USER" = "" ]
-then
-    if [ "$SSH_CLIENT" != ""  ] && [ "$OAR_KEY" != "1" ]
-    then
+if [ "$OAR_JOB_USER" = "" ]; then
+    if [ "$SSH_CLIENT" != ""  ] && [ "$OAR_KEY" != "1" ]; then
         echo "oarsh: The OAR_KEY environment variable is not defined and this seems to be a oar user connection." 1>&2
         exit 65
     fi
     # It must be oar
-    if [ "$OAR_CPUSET" != "" ]
-    then
+    if [ "$OAR_CPUSET" != "" ]; then
         add_process_to_cpuset $OAR_CPUSET $$ $PPID || exit 62
-        [ -r "$JOBENVFILE" ] && source $JOBENVFILE
+        [ -r "$JOBENVFILE" ] && . $JOBENVFILE
     fi
     $OARDIR/oardodo/oardodo renice 0 $$ $PPID > /dev/null 2>&1
     export SHELL=$DEFAULT_SHELL
-    
     umask $OLDUMASK
     exec $DEFAULT_SHELL "$@"
     echo "oarsh: exec failed" 1>&2
     exit 66
 else
-    if [ "$OAR_CPUSET" = "" ]
-    then
+    if [ "$OAR_CPUSET" = "" ]; then
         echo "oarsh: OAR_CPUSET variable is empty; Is your sshd right configured with 'AcceptEnv OAR_CPUSET OAR_JOB_USER' on all computing nodes?" 1>&2
         exit 63
     fi
     add_process_to_cpuset $OAR_CPUSET $$ $PPID || exit 62
-    
     #Manage display
-    if [ -n "$DISPLAY" ]
-    then
-        if [ -x "$XAUTH_LOCATION" ]
-        then
+    if [ -n "$DISPLAY" ]; then
+        if [ -x "$XAUTH_LOCATION" ]; then
             $XAUTH_LOCATION -q extract - ${DISPLAY#localhost} | OARDO_BECOME_USER=${OAR_JOB_USER} $OARDIR/oardodo/oardodo $XAUTH_LOCATION merge -
             [ "${OAR_JOB_USER}" != "$OAR_JOB_USER" ] && OARDO_BECOME_USER=${OAR_JOB_USER} $OARDIR/oardodo/oardodo bash --noprofile --norc -c 'chmod 660 $HOME/.Xauthority'
         fi
@@ -176,9 +164,8 @@ else
     #Change tty owner
     TTY=$(tty) && test -e $TTY && $OARDIR/oardodo/oardodo chown $OAR_JOB_USER:oar $TTY && $OARDIR/oardodo/oardodo chmod 660 $TTY
     $OARDIR/oardodo/oardodo renice 0 $$ $PPID > /dev/null 2>&1
-    [ -r "$JOBENVFILE" ] && source $JOBENVFILE
-    if [ "$1" = "" ]
-    then
+    [ -r "$JOBENVFILE" ] && . $JOBENVFILE
+    if [ "$1" = "" ]; then
         # Simulate initial login
         export OARDO_BECOME_USER=$OAR_JOB_USER
         umask $OLDUMASK
@@ -198,4 +185,3 @@ fi
 
 echo "oarsh: Really bad error" 1>&2
 exit 67
-`
