[pam] rewrite pam_oar_adopt and its documentation

diff --git a/sources/core/tools/oarsh/pam_oar_adopt b/sources/core/tools/oarsh/pam_oar_adopt
--- a/sources/core/tools/oarsh/pam_oar_adopt
+++ b/sources/core/tools/oarsh/pam_oar_adopt
@@ -16,6 +16,45 @@ CGROUP_MOUNT_POINT=$(sed -ne 's/^[^ ]\+ \([^ ]\+\) cgroup2 .*/\1/p' /proc/mounts
 OAR_CGROUP_BASE="$CGROUP_MOUNT_POINT/oar.slice"
 USER_UID_MIN=1000
 
+exit_with_warning_or_error() {
+    if [ "$MODE" = "enforced" ]; then
+	printf "$1\n\n" 1>&2
+	exit 1
+    elif [ "$WARN" = true ]; then
+	printf "pam_oar_adopt disabled, warns only: %s\n" "$1"
+    fi
+    exit 0
+}
+
+pam_oar_adopt_load_config() {
+    if [ -f "/etc/oar/pam_oar_adopt_enabled" ]; then
+        MODE="enforced"
+    else
+        MODE="disabled"
+    fi
+    WARN=true
+
+    if [ -r /etc/oar/pam_oar_adopt.conf ]; then
+        . /etc/oar/pam_oar_adopt.conf
+    fi
+
+    case "$MODE" in
+        enforced|disabled) ;;
+	*)
+	    echo "Invalid value for MODE in /etc/oar/pam_oar_adopt.conf." 1>&2
+	    exit 0
+	    ;;
+    esac
+    case "${WARN,,}" in
+	1|yes|on|true) WARN=true ;;
+	0|no|off|false) WARN=false ;;
+	*)
+	    echo "Invalid value for WARN in /etc/oar/pam_oar_adopt.conf." 1>&2
+	    WARN=true
+	    ;;
+    esac
+}
+
 get_oar_cgroups_of_user() {
     # Exit if the PAM service is not sshd (e.g. su, su-l, sudo, sudo-i, ...)
     if [ "$PAM_SERVICE" != "sshd" ]; then
@@ -38,13 +77,9 @@ get_oar_cgroups_of_user() {
         exit 0
     fi
 
-    # Exit if oar.slice does not exist (job_resource_manager did not run yet, not job run since last reboot)
     if [ ! -d "$OAR_CGROUP_BASE" ]; then
-        cat <<EOF 1>&2
-No running job found for $OAR_USER on this node.
-
-EOF
-        exit 1
+        # Exit if oar.slice does not exist (job_resource_manager did not run yet, not job run since last reboot)
+        exit_with_warning_or_error "No running job found for $OAR_USER on this node."
     fi
 
     readarray -t OAR_SLICES < <( cd "$OAR_CGROUP_BASE" && ls -d "oar-u$USER_UID.slice/oar-u$USER_UID"-j*.slice 2>/dev/null )
@@ -52,7 +87,7 @@ EOF
 }
 
 pam_account() {
-    pam_oar_adopt_enabled_or_exit
+    pam_oar_adopt_load_config
 
     get_oar_cgroups_of_user
 
@@ -61,34 +96,22 @@ pam_account() {
     # - the user has more than one cgroup or one but without all cores
     # - the user has one cgroup with all cores
     if [ -z "$OAR_SLICE" ]; then
-        cat <<EOF 1>&2
-No running job found for $OAR_USER on this node.
-
-EOF
-        exit 1
+        exit_with_warning_or_error "No running job found for $OAR_USER on this node."
     elif [ ${#OAR_SLICES[*]} -ne 1 ]; then
-        cat << EOF 1>&2
-Cannot connect to node using 'ssh', because it appears there are more than one
+        exit_with_warning_or_error "Cannot connect to node using 'ssh', because it appears there are more than one
 job on running on the node. Make sure to only have one job on the node, or use
-'oarsh' to connect to a specific job.
-
-EOF
-        exit 1
+'oarsh' to connect to a specific job."
     elif [ "$(< "$OAR_CGROUP_BASE/$OAR_SLICE"/cpuset.cpus.effective)" != "$(< "${OAR_CGROUP_BASE}"/cpuset.cpus.effective)" ]; then
-        cat << EOF 1>&2
-Cannot connect to node using 'ssh' because not all its compute resources
+        exit_with_warning_or_error "Cannot connect to node using 'ssh' because not all its compute resources
 (e.g. CPU cores or threads) are assigned to the job which reserves it.
-Reserve the whole node, or use 'oarsh' instead.
-
-EOF
-        exit 1
+Reserve the whole node, or use 'oarsh' instead."
     else
         exit 0
     fi
 }
 
 pam_session() {
-    pam_oar_adopt_enabled_or_exit
+    pam_oar_adopt_load_config
 
     get_oar_cgroups_of_user
 
@@ -110,16 +133,23 @@ pam_session() {
     fi
 
     if [ ! -d /var/lib/oar ]; then
-        echo "OAR directory not found: /var/lib/oar." 1>&2
-        exit 1
+        exit_with_warning_or_error "OAR directory not found: /var/lib/oar."
     fi
+
+    if [ "$MODE" != enforced ]; then
+        if [ "$WARN" = true ]; then
+	    printf "pam_oar_adopt disabled, not adding job into cgroup.\n"
+	fi
+        return 0
+    fi
+    # We are in enforced mode here, handling cgroup assignment
 
     # To have the job environment variables, we create a symkink to the already
     # created job environment file and let pam_env load it.
     OAR_JOB_ENV=${OAR_SLICE%.slice}
     OAR_JOB_ENV=/var/lib/oar/${OAR_USER}_${OAR_JOB_ENV#*-j}.env
     if [ ! -e "$OAR_JOB_ENV" ]; then
-        echo "Could not find job env file." 1>&2
+        echo "OAR directory not found: /var/lib/oar." 1>&2
         exit 1
     fi
 
@@ -132,12 +162,6 @@ pam_session() {
     while busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListJobs | grep -q "$SYSTEMD_PROC_SCOPE"; do
         sleep 0.1
     done
-}
-
-pam_oar_adopt_enabled_or_exit() {
-    if [ ! -f "/etc/oar/pam_oar_adopt_enabled" ]; then
-        exit 0
-    fi
 }
 
 if [ $# -eq 0 ]; then
