Remove most of the debconf stuff to handle configuration, because it might overwrite a configuration modified by the user on upgrade.

diff --git a/debian/oar-user.postinst b/debian/oar-user.postinst
--- a/debian/oar-user.postinst
+++ b/debian/oar-user.postinst
@@ -22,64 +22,64 @@ set -e
 . /usr/share/debconf/confmodule
 db_version 2.0
 
-setup_conf() {
-	if [ ! -r /etc/oar/oar.conf ]; then
-		echo "Error: No /etc/oar/oar.conf found."
-		exit 1
-	fi
-	db_get oar/db/hostname
-	DB_HOSTNAME=$RET
-	db_get oar/db/basename
-	DB_BASE_NAME=$RET
-	db_get oar/db/baselogin
-	DB_BASE_LOGIN=$RET
-	db_get oar/db/basepasswd
-	DB_BASE_PASSWD=$RET
-
-	db_get oar/server/hostname
-	SERVER_HOSTNAME=$RET
-	db_get oar/server/port
-	SERVER_PORT=$RET
-	perl -i -pe \
-		"s/^DB_HOSTNAME=.*/DB_HOSTNAME=$DB_HOSTNAME/;
-		s/^DB_BASE_NAME=.*/DB_BASE_NAME=$DB_BASE_NAME/;
-		s/^DB_BASE_LOGIN=.*/DB_BASE_LOGIN=$DB_BASE_LOGIN/;
-		s/^DB_BASE_PASSWD=.*/DB_BASE_PASSWD=$DB_BASE_PASSWD/;
-		s/^SERVER_HOSTNAME=.*/SERVER_HOSTNAME=$SERVER_HOSTNAME/;
-		s/^SERVER_PORT=.*/SERVER_PORT=$SERVER_PORT/;" \
-		/etc/oar/oar.conf
-	chown oar:root /etc/oar/oar.conf
-	chmod 0600 /etc/oar/oar.conf
-}
-
-setup_ssh() {
-	db_get oar/server/hostname
-	SERVER_HOSTNAME=$RET
-	if [ $SERVER_HOSTNAME != "localhost" ]; then
-		ssh -x -o StrictHostKeyChecking=no $SERVER_HOSTNAME tar c -C /var/lib/oar/ .ssh | tar x -C /var/lib/oar/
-	fi
-}
-
-setup_users() {
-	db_get oar/user/dosetup
-	if [ "x$RET" = "xtrue" ]; then
-		db_get oar/user/listmethod
-		if [ "x$RET" = "xinline" ]; then
-			db_get oar/user/listinline
-			for u in `echo $RET`; do
-				adduser $u oar || true
-			done
-		elif [ "x$RET" = "xfile" ]; then
-			db_get oar/user/listfile
-			for u in `cat $RET`; do
-				adduser $u oar || true
-			done
-		fi
-	fi
-}
-
-setup_conf
-setup_ssh
+#setup_conf() {
+#	if [ ! -r /etc/oar/oar.conf ]; then
+#		echo "Error: No /etc/oar/oar.conf found."
+#		exit 1
+#	fi
+#	db_get oar/db/hostname
+#	DB_HOSTNAME=$RET
+#	db_get oar/db/basename
+#	DB_BASE_NAME=$RET
+#	db_get oar/db/baselogin
+#	DB_BASE_LOGIN=$RET
+#	db_get oar/db/basepasswd
+#	DB_BASE_PASSWD=$RET
+#
+#	db_get oar/server/hostname
+#	SERVER_HOSTNAME=$RET
+#	db_get oar/server/port
+#	SERVER_PORT=$RET
+#	perl -i -pe \
+#		"s/^DB_HOSTNAME=.*/DB_HOSTNAME=$DB_HOSTNAME/;
+#		s/^DB_BASE_NAME=.*/DB_BASE_NAME=$DB_BASE_NAME/;
+#		s/^DB_BASE_LOGIN=.*/DB_BASE_LOGIN=$DB_BASE_LOGIN/;
+#		s/^DB_BASE_PASSWD=.*/DB_BASE_PASSWD=$DB_BASE_PASSWD/;
+#		s/^SERVER_HOSTNAME=.*/SERVER_HOSTNAME=$SERVER_HOSTNAME/;
+#		s/^SERVER_PORT=.*/SERVER_PORT=$SERVER_PORT/;" \
+#		/etc/oar/oar.conf
+#	chown oar:root /etc/oar/oar.conf
+#	chmod 0600 /etc/oar/oar.conf
+#}
+#
+#setup_ssh() {
+#	db_get oar/server/hostname
+#	SERVER_HOSTNAME=$RET
+#	if [ $SERVER_HOSTNAME != "localhost" ]; then
+#		ssh -x -o StrictHostKeyChecking=no $SERVER_HOSTNAME tar c -C /var/lib/oar/ .ssh | tar x -C /var/lib/oar/
+#	fi
+#}
+#
+#setup_users() {
+#	db_get oar/user/dosetup
+#	if [ "x$RET" = "xtrue" ]; then
+#		db_get oar/user/listmethod
+#		if [ "x$RET" = "xinline" ]; then
+#			db_get oar/user/listinline
+#			for u in `echo $RET`; do
+#				adduser $u oar || true
+#			done
+#		elif [ "x$RET" = "xfile" ]; then
+#			db_get oar/user/listfile
+#			for u in `cat $RET`; do
+#				adduser $u oar || true
+#			done
+#		fi
+#	fi
+#}
+#
+#setup_conf
+#setup_ssh
 #setup_users
 
 # dh_installdeb will replace this with shell code automatically
