Commit modification script installtion, peut engendrer des erreurs, attention!

diff --git a/FaultTolerance/HAinstal b/FaultTolerance/HAinstal
--- a/FaultTolerance/HAinstal
+++ b/FaultTolerance/HAinstal
@@ -17,16 +17,16 @@ MODULEASSITANT="module-assistant"
 
 ####--BDD---#####
 # "mysql" or "postgresql"
-BD="postgresql"
+BD="mysql"
 ##only for postgres
 PGVERSION="8.3"
 
 ###----Nodes name-----------####
 
-MASTER_OAR="genepi-7.grenoble.grid5000.fr"
-MASTER_DB="genepi-7.grenoble.grid5000.fr"
-BACKUP_OAR="genepi-9.grenoble.grid5000.fr"
-BACKUP_DB="genepi-9.grenoble.grid5000.fr"
+MASTER_OAR="genepi-6.grenoble.grid5000.fr"
+MASTER_DB="genepi-21.grenoble.grid5000.fr"
+BACKUP_OAR="genepi-29.grenoble.grid5000.fr"
+BACKUP_DB="genepi-31.grenoble.grid5000.fr"
 
 #-----Nodes properties-----####
 #Interface
@@ -91,21 +91,37 @@ DBRDPORT="7788"
 
 HOSTNAME=$(uname -n)
 
+#High Availability configuration : "2nodes" or "4nodes"
+if [ "$MASTER_OAR" = "$MASTER_DB" ]; then
+	CONF="2nodes"
+else
+	CONF="4nodes"
+fi
+
+
 case $HOSTNAME in
 $MASTER_OAR)
-	ISOAR="y"
-	ISDATABASE="n"
+	ISMASTER="y"
+	if [ "$CONF" = "2nodes" ]; then
+		ISDATABASE="y"
+	else
+		ISDATABASE="n"
+	fi
 	;;
 $MASTER_DB)
-	ISOAR="y"
+	ISMASTER="y"
 	ISDATABASE="y"
 	;;
 $BACKUP_OAR)
-	ISOAR="n"
-	ISDATABASE="n"
+	ISMASTER="n"
+	if [ "$CONF" = "2nodes" ]; then
+		ISDATABASE="y"
+	else
+		ISDATABASE="n"
+	fi
 	;;
 $BACKUP_DB)
-	ISOAR="n"
+	ISMASTER="n"
 	ISDATABASE="y"
 	;;
 *)
@@ -114,14 +130,6 @@ $BACKUP_DB)
 	exit 1
 	;;
 esac
-
-
-#High Availability configuration : "2nodes" or "4nodes"
-if [ "$MASTER_OAR" = "$MASTER_DB" ]; then
-	CONF="2nodes"
-else
-	CONF="4nodes"
-fi
 
 echo "You are now ready to configure High Availabity with $CONF configuration"
 echo "Press enter to continue ..."
@@ -163,7 +171,7 @@ exists update-rc.d
 
 #-----------------------Installation on debian---------------------------------------------------
 apt-get update
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	apt-get -y install $DRBD $MODULEASSITANT
 	#installation test
 	exists module-assistant
@@ -175,18 +183,20 @@ apt-get -y install $HEARTBEAT2 host
 exists host
 
 #-----------------------Stop services---------------------------------------------------
-if [ "$BD" = "mysql" ]; then
-	/etc/init.d/$BD stop
-elif [ "$BD" = "postgresql" ]; then
-	/etc/init.d/$BD"-"$PGVERSION stop
-else
-	exit 1
+if [ "$ISDATABASE" = "y" ]; then
+	if [ "$BD" = "mysql" ]; then
+		/etc/init.d/$BD stop
+	elif [ "$BD" = "postgresql" ]; then
+		/etc/init.d/$BD"-"$PGVERSION stop
+	else
+		exit 1
+	fi
 fi
 if [ "$ISDATABASE" = "n" ]||[ "$CONF" = "2nodes" ]; then
 	/etc/init.d/oar-server stop
 fi
 
-#-----------------------Delete old configurations---------------------------------------------------
+#-----------------------Delete old heartbeat configurations---------------------------------------------------
 
 if [ -f /var/lib/heartbeat/crm/cib.xml ]; then
 	rm /var/lib/heartbeat/crm/cib.xml
@@ -216,7 +226,7 @@ echo 'keepalive 1 # 1 second' >> /etc/ha.d/ha.cf
 echo 'deadtime 10' >> /etc/ha.d/ha.cf
 echo 'initdead 80' >> /etc/ha.d/ha.cf
 
-if [ "$ISOAR" = "y" ]; then
+if [ "$ISMASTER" = "y" ]; then
 	if [ "$ISDATABASE" = "y" ]; then
 		ipmaster_oar=$(host $MASTER_OAR | cut -f3)
 		ipmaster_db=$(host `uname -n` | cut -f3)	#don't use ifconfig beacause can beug if it is a non english system
@@ -228,7 +238,7 @@ if [ "$ISOAR" = "y" ]; then
 		ipbackup_oar=$(host $BACKUP_OAR | cut -f3)
 		ipbackup_db=$(host $BACKUP_DB | cut -f3)
 	fi	
-elif [ "$ISOAR" = "n" ]; then
+elif [ "$ISMASTER" = "n" ]; then
 	if [ "$ISDATABASE" = "y" ]; then
 		ipmaster_oar=$(host $MASTER_OAR | cut -f3)
 		ipmaster_db=$(host $MASTER_DB | cut -f3)
@@ -708,7 +718,7 @@ elif [ "$CONF" = "2nodes" ]; then 	#2nodes configuration, very important, becaus
 fi
 
 #-----------------------Get database data path for DRBD configuration, and change this path---------------------------------------------------
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	if [ "$BD" = "mysql" ]; then
 		mysqldirold=$(cat /etc/$BD/my.cnf | grep datadir | cut -d "=" -f2)
 		mysqldiroldn=$(echo $mysqldirold | sed 's/\//\\\//g')
@@ -735,7 +745,7 @@ fi
 
 #-----------------------DRBD Configuration---------------------------------------------------
 
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	echo 'global { usage-count no; }' > /etc/drbd.conf
 
 	echo 'resource mysql {' >> /etc/drbd.conf
@@ -749,31 +759,20 @@ if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
 	echo '	protocol C;' >> /etc/drbd.conf
 
 	echo '	startup {' >> /etc/drbd.conf
-	echo '		# Au démarrage du noeud, on attend (cela bloque le' >> /etc/drbd.conf
-	echo '		# démarrage) le noeud distant pendant 2 minutes.' >> /etc/drbd.conf
+	echo '		# when the node start, wait 2 minutes others nodes' >> /etc/drbd.conf
 	echo '		wfc-timeout 120;' >> /etc/drbd.conf
 	echo '	}' >> /etc/drbd.conf
 
-	echo '	# Si une erreur d entrée sortie est rencontrée avec le sous' >> /etc/drbd.conf
-	echo '	# volume physique, on freeze la machine et' >> /etc/drbd.conf
-	echo '	# Heartbeat basculera l exploitation sur l autre machine' >> /etc/drbd.conf
+	echo '	# If io-error, freeze node' >> /etc/drbd.conf
 	echo '	disk {' >> /etc/drbd.conf
 	echo '		on-io-error detach;' >> /etc/drbd.conf
 	echo '	}' >> /etc/drbd.conf
 
 	echo '	syncer {' >> /etc/drbd.conf
 	echo '		rate 700000K;' >> /etc/drbd.conf
-	echo '		# On ne limite pas la vitesse de synchronisation.' >> /etc/drbd.conf
+	echo '		# Rate of synchronization. max 700000K' >> /etc/drbd.conf
 	echo '		al-extents 257;' >> /etc/drbd.conf
-	echo '		# al-extent définit la taille de la « hot-area » : DRBD' >> /etc/drbd.conf
-	echo '		# stocke en permanence dans les meta-data les zones' >> /etc/drbd.conf
-	echo '		# actives du volume physique. En cas de crash ces zones' >> /etc/drbd.conf
-	echo '		# seront ainsi resynchronisées dès le retour du' >> /etc/drbd.conf
-	echo '		# noeud. Chaque extent définit une zone de 4Mo. Plus al-' >> /etc/drbd.conf
-	echo '		# extents est grand, plus la resynchronisation après un' >> /etc/drbd.conf
-	echo '		# crash sera longue, mais il y aura moins d écritures de' >> /etc/drbd.conf
-	echo '		# meta-data.' >> /etc/drbd.conf
-	echo '		# Avec 257 on a donc 1giga de « hot aera ».' >> /etc/drbd.conf
+	echo '		# al-extent is the size of the « hot-area »' >> /etc/drbd.conf
 	echo '	}' >> /etc/drbd.conf
 
 	echo "	on $MASTER_DB {" >> /etc/drbd.conf
@@ -814,7 +813,7 @@ fi
 #-----------------------Create the device for DRBD Data---------------------------------------------------
 
 
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 
 	modprobe drbd
 
@@ -840,7 +839,7 @@ if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
 	fi
 
 	#On the master
-	if [ "$ISOAR" = "y" ]; then
+	if [ "$ISMASTER" = "y" ]&&[ "$ISDATABASE" = "y" ]; then
 		#The master launch syncrhonization
 		drbdadm -- --overwrite-data-of-peer primary all
 
@@ -871,8 +870,7 @@ fi
 
 #-----------------------Remove auto launch---------------------------------------------------
 
-update-rc.d -f oar-server remove
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	if [ "$BD" = "mysql" ]; then
 		update-rc.d -f $BD remove
 	elif [ "$BD" = "postgresql" ]; then
@@ -880,6 +878,9 @@ if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
 	else
 		exit 1
 	fi
+fi
+if [ "$ISDATABASE" = "n" ]||[ "$CONF" = "2nodes" ] ; then
+	update-rc.d -f oar-server remove
 fi
 
 #-----------------------Create service for auto associate $LOOPBACK with $IMAGE-----------------------------
diff --git a/FaultTolerance/HAinstal-Centos b/FaultTolerance/HAinstal-Centos
--- a/FaultTolerance/HAinstal-Centos
+++ b/FaultTolerance/HAinstal-Centos
@@ -31,10 +31,10 @@ PGVERSION="8.3"
 
 ###----Nodes name-----------####
 
-MASTER_OAR="grelon-57"
-MASTER_DB="grelon-57"
-BACKUP_OAR="grelon-58"
-BACKUP_DB="grelon-58"
+MASTER_OAR="grelon-39"
+MASTER_DB="grelon-40"
+BACKUP_OAR="grelon-41"
+BACKUP_DB="grelon-42"
 
 #-----Nodes properties-----####
 #Interface
@@ -99,21 +99,37 @@ DBRDPORT="7788"
 
 HOSTNAME=$(uname -n)
 
+#High Availability configuration : "2nodes" or "4nodes"
+if [ "$MASTER_OAR" = "$MASTER_DB" ]; then
+	CONF="2nodes"
+else
+	CONF="4nodes"
+fi
+
+
 case $HOSTNAME in
 $MASTER_OAR)
-	ISOAR="y"
-	ISDATABASE="n"
+	ISMASTER="y"
+	if [ "$CONF" = "2nodes" ]; then
+		ISDATABASE="y"
+	else
+		ISDATABASE="n"
+	fi
 	;;
 $MASTER_DB)
-	ISOAR="y"
+	ISMASTER="y"
 	ISDATABASE="y"
 	;;
 $BACKUP_OAR)
-	ISOAR="n"
-	ISDATABASE="n"
+	ISMASTER="n"
+	if [ "$CONF" = "2nodes" ]; then
+		ISDATABASE="y"
+	else
+		ISDATABASE="n"
+	fi
 	;;
 $BACKUP_DB)
-	ISOAR="n"
+	ISMASTER="n"
 	ISDATABASE="y"
 	;;
 *)
@@ -124,12 +140,7 @@ $BACKUP_DB)
 esac
 
 
-#High Availability configuration : "2nodes" or "4nodes"
-if [ "$MASTER_OAR" = "$MASTER_DB" ]; then
-	CONF="2nodes"
-else
-	CONF="4nodes"
-fi
+
 
 echo "You are now ready to configure High Availabity with $CONF configuration"
 echo "Press enter to continue ..."
@@ -171,31 +182,34 @@ exists host
 
 #-----------------------Installation on debian---------------------------------------------------
 
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	yum -y install $DRBD $DRBDKMOD
+	exists drbdadm		#DRBD test
 fi
 
 yum -y install $HEARTBEAT2
+yum -y install $HEARTBEAT2	#2 times beacause there is a bug ...
 
 #-----Installation tests-----#
 
 exists crmadmin		#Heartbeat test
-exists drbdadm		#DRBD test
 
 
 #-----------------------Stop services---------------------------------------------------
-if [ "$BD" = "mysql" ]; then
-	/etc/init.d/$BD"d" stop
-elif [ "$BD" = "postgresql" ]; then
-	/etc/init.d/$BD"-"$PGVERSION stop
-else
-	exit 1
+if [ "$ISDATABASE" = "y" ]; then
+	if [ "$BD" = "mysql" ]; then
+		/etc/init.d/$BD"d" stop
+	elif [ "$BD" = "postgresql" ]; then
+		/etc/init.d/$BD"-"$PGVERSION stop
+	else
+		exit 1
+	fi
 fi
 if [ "$ISDATABASE" = "n" ]||[ "$CONF" = "2nodes" ]; then
 	/etc/init.d/oar-server stop
 fi
 
-#-----------------------Delete old configurations---------------------------------------------------
+#-----------------------Delete old heartbeat configurations---------------------------------------------------
 
 if [ -f /var/lib/heartbeat/crm/cib.xml ]; then
 	rm /var/lib/heartbeat/crm/cib.xml
@@ -225,7 +239,7 @@ echo 'keepalive 1 # 1 second' >> /etc/ha.d/ha.cf
 echo 'deadtime 10' >> /etc/ha.d/ha.cf
 echo 'initdead 80' >> /etc/ha.d/ha.cf
 
-if [ "$ISOAR" = "y" ]; then
+if [ "$ISMASTER" = "y" ]; then
 	if [ "$ISDATABASE" = "y" ]; then
 		ipmaster_oar=$(host $MASTER_OAR | cut -d" " -f4)
 		ipmaster_db=$(host `uname -n` | cut -d" " -f4)	#don't use ifconfig beacause can beug if it is a non english system
@@ -237,7 +251,7 @@ if [ "$ISOAR" = "y" ]; then
 		ipbackup_oar=$(host $BACKUP_OAR | cut -d" " -f4)
 		ipbackup_db=$(host $BACKUP_DB | cut -d" " -f4)
 	fi	
-elif [ "$ISOAR" = "n" ]; then
+elif [ "$ISMASTER" = "n" ]; then
 	if [ "$ISDATABASE" = "y" ]; then
 		ipmaster_oar=$(host $MASTER_OAR | cut -d" " -f4)
 		ipmaster_db=$(host $MASTER_DB | cut -d" " -f4)
@@ -723,7 +737,7 @@ fi
 
 #-----------------------Modify mysql service, for return 0 if mysql is stopped and you try to stop it---------------------------------------------------
 
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 
 	sed -e "s/stop(){/stop(){\n\tstatus mysqld\n\tif [ \$? -eq 3 ]; then\n\t\taction \$\"Stopping \$prog: \" \/bin\/true\n\t\texit 0\n\tfi\n/g" /etc/init.d/mysqld > /etc/init.d/mysqld.tmp && mv -f /etc/init.d/mysqld.tmp /etc/init.d/mysqld
 
@@ -751,7 +765,7 @@ elif [ "$CONF" = "2nodes" ]; then 	#2nodes configuration, very important, becaus
 fi
 
 #-----------------------Get database data path for DRBD configuration, and change this path---------------------------------------------------
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	if [ "$BD" = "mysql" ]; then
 		datadirold=$(cat /etc/my.cnf | grep datadir)
 		datadiroldn=$(echo $datadirold | sed 's/\//\\\//g')
@@ -780,7 +794,7 @@ fi
 
 #-----------------------DRBD Configuration---------------------------------------------------
 
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	echo 'global { usage-count no; }' > /etc/drbd.conf
 
 	echo 'resource mysql {' >> /etc/drbd.conf
@@ -794,31 +808,20 @@ if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
 	echo '	protocol C;' >> /etc/drbd.conf
 
 	echo '	startup {' >> /etc/drbd.conf
-	echo '		# Au démarrage du noeud, on attend (cela bloque le' >> /etc/drbd.conf
-	echo '		# démarrage) le noeud distant pendant 2 minutes.' >> /etc/drbd.conf
+	echo '		# when the node start, wait 2 minutes others nodes' >> /etc/drbd.conf
 	echo '		wfc-timeout 120;' >> /etc/drbd.conf
 	echo '	}' >> /etc/drbd.conf
 
-	echo '	# Si une erreur d entrée sortie est rencontrée avec le sous' >> /etc/drbd.conf
-	echo '	# volume physique, on freeze la machine et' >> /etc/drbd.conf
-	echo '	# Heartbeat basculera l exploitation sur l autre machine' >> /etc/drbd.conf
+	echo '	# If io-error, freeze node' >> /etc/drbd.conf
 	echo '	disk {' >> /etc/drbd.conf
 	echo '		on-io-error detach;' >> /etc/drbd.conf
 	echo '	}' >> /etc/drbd.conf
 
 	echo '	syncer {' >> /etc/drbd.conf
 	echo '		rate 700000K;' >> /etc/drbd.conf
-	echo '		# On ne limite pas la vitesse de synchronisation.' >> /etc/drbd.conf
+	echo '		# Rate of synchronization. max 700000K' >> /etc/drbd.conf
 	echo '		al-extents 257;' >> /etc/drbd.conf
-	echo '		# al-extent définit la taille de la « hot-area » : DRBD' >> /etc/drbd.conf
-	echo '		# stocke en permanence dans les meta-data les zones' >> /etc/drbd.conf
-	echo '		# actives du volume physique. En cas de crash ces zones' >> /etc/drbd.conf
-	echo '		# seront ainsi resynchronisées dès le retour du' >> /etc/drbd.conf
-	echo '		# noeud. Chaque extent définit une zone de 4Mo. Plus al-' >> /etc/drbd.conf
-	echo '		# extents est grand, plus la resynchronisation après un' >> /etc/drbd.conf
-	echo '		# crash sera longue, mais il y aura moins d écritures de' >> /etc/drbd.conf
-	echo '		# meta-data.' >> /etc/drbd.conf
-	echo '		# Avec 257 on a donc 1giga de « hot aera ».' >> /etc/drbd.conf
+	echo '		# al-extent is the size of the « hot-area »' >> /etc/drbd.conf
 	echo '	}' >> /etc/drbd.conf
 
 	echo "	on $MASTER_DB {" >> /etc/drbd.conf
@@ -859,7 +862,7 @@ fi
 #-----------------------Create the device for DRBD Data---------------------------------------------------
 
 
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 
 	modprobe drbd
 
@@ -887,7 +890,7 @@ if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
 	fi
 
 	#On the master
-	if [ "$ISOAR" = "y" ]; then
+	if [ "$ISMASTER" = "y" ]&&[ "$ISDATABASE" = "y" ]; then
 		#The master launch syncrhonization
 		drbdadm -- --overwrite-data-of-peer primary all
 
@@ -919,8 +922,7 @@ fi
 #-----------------------Remove auto launch---------------------------------------------------
 
 chkconfig --add heartbeat
-chkconfig oar-server off
-if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
+if [ "$ISDATABASE" = "y" ]; then
 	if [ "$BD" = "mysql" ]; then
 		chkconfig $BD"d" off
 	elif [ "$BD" = "postgresql" ]; then
@@ -929,6 +931,9 @@ if [ "$ISDATABASE" = "y" ]||[ "$CONF" = "2nodes" ]; then
 	else
 		exit 1
 	fi
+fi
+if [ "$ISDATABASE" = "n" ]||[ "$CONF" = "2nodes" ] ; then
+	chkconfig oar-server off
 fi
 
 
@@ -964,7 +969,7 @@ chkconfig --level 2345 active-loop on
 #-----------------------Launch heartbeat service---------------------------------------------------
 
 #to be deleted, because can fail with DRBD
-/etc/init.d/heartbeat start
+#/etc/init.d/heartbeat start
 
 #-----------------------Add cgi script for monitor heartbeat---------------------------------------------------
 
