[sbuildrpm] minor fixes + more doc

diff --git a/sbuildrpm/bin/sbuildrpm b/sbuildrpm/bin/sbuildrpm
--- a/sbuildrpm/bin/sbuildrpm
+++ b/sbuildrpm/bin/sbuildrpm
@@ -6,7 +6,7 @@ umask 0002
 ######################
 
 die() {
-  echo $@ 1>&2
+  echo "Error: $@" 1>&2
   exit 1
 }
 
@@ -77,20 +77,20 @@ do
     usage
     exit 0
   ;;
-  *)
+  \?)
     usage
-    exit 1
+    exit 1 
   ;;
   esac
 done
 shift $((OPTIND - 1))
-echo $@
 
 SPEC_FILE=$1
+[ -n "$SPEC_FILE" ] || (usage && die "Please give me a SPEC file to eat")
 [ -r $SPEC_FILE ] || die "Could not read SPEC file: $SPEC_FILE"
-BASE_DIR=${SPEC_FILE%/rpm/SPECS/*.spec}
-TARBALLS_DIR=$BASE_DIR/../tarballs
-RPMBUILD_DIR=$BASE_DIR/../rpmbuild
+BASE_DIR=${SPEC_FILE%rpm/SPECS/*.spec}
+TARBALLS_DIR=$BASE_DIR../tarballs
+RPMBUILD_DIR=$BASE_DIR../rpmbuild
 
 NAME=$(grep -e "^Name:" $SPEC_FILE | sed -e "s/^Name:[[:space:]]\+//")
 SOURCE0=$(grep -e "^Source0:" $SPEC_FILE | sed -e "s/^Source0:[[:space:]]\+//")
