[centos6] minor fixes

diff --git a/sbuildrpm/bin/sbuildrpm b/sbuildrpm/bin/sbuildrpm
--- a/sbuildrpm/bin/sbuildrpm
+++ b/sbuildrpm/bin/sbuildrpm
@@ -6,34 +6,34 @@ umask 0002
 ######################
 
 die() {
-	echo $@ 1>&2
-	exit 1
+  echo $@ 1>&2
+  exit 1
 }
 
 cleanup() {
-	set +e
-	if [ -n "$KEEP_SESSION" ]; then
-		[ -n "$CHROOT_SESSION" ] && echo "Keeping schroot session open, run 'schroot -c $CHROOT_SESSION -e' to end it"
-		[ -n "$SBUILDRPM_BUILD_DIR" ] && echo "Build directory not deleted, run 'rm -rf $SBUILDRPM_BUILD_DIR' to delete it."
-	else
-		[ -n "$CHROOT_SESSION" ] && schroot -c $CHROOT_SESSION -e
-		[ -n "$SBUILDRPM_BUILD_DIR" ] && rm -rf $SBUILDRPM_BUILD_DIR
-		echo "Cleaned up !"
-	fi
+  set +e
+  if [ -n "$KEEP_SESSION" ]; then
+    [ -n "$CHROOT_SESSION" ] && echo "Keeping schroot session open, run 'schroot -c $CHROOT_SESSION -e' to end it"
+    [ -n "$SBUILDRPM_BUILD_DIR" ] && echo "Build directory not deleted, run 'rm -rf $SBUILDRPM_BUILD_DIR' to delete it."
+  else
+    [ -n "$CHROOT_SESSION" ] && schroot -c $CHROOT_SESSION -e
+    [ -n "$SBUILDRPM_BUILD_DIR" ] && rm -rf $SBUILDRPM_BUILD_DIR
+    echo "Cleaned up !"
+  fi
 }
 
 trap_error() {
-	cleanup
-	echo "BAD" 
-	exit 1
+  cleanup
+  echo "BAD" 
+  exit 1
 }
 
 usage() {
-	cat 1>&2 <<EOF
+ cat 1>&2 <<EOF
 Usage: $0 [-l] [-k] <SPEC file>
 Options:
-	-l	run rpmlint and exit if some error are reported
-	-k	keep the schroot session open
+ -l run rpmlint and exit if some error are reported
+ -k keep the schroot session open
 EOF
 }
 
@@ -45,19 +45,19 @@ trap trap_error ERR
 
 CHROOT_NAME="chroot:centos6-amd64"
 if ! schroot -l | grep -q -e "^$CHROOT_NAME$"; then
-	die "CentOS 6 chroot not found."
+  die "CentOS 6 chroot not found."
 fi
 
 if ! id | grep -q "(sbuild)"; then 
-	echo "You need to be part of the sbuild group, adding you..."
-	sudo adduser $USER sbuild
-	die "Please logout and login again, so that your new group membership is taken into account."
+  echo "You need to be part of the sbuild group, adding you..."
+  sudo adduser $USER sbuild
+  die "Please logout and login again, so that your new group membership is taken into account."
 fi
 
 SBUILDRPM_DIR=/var/lib/sbuildrpm
 if [ ! -d $SBUILDRPM_DIR ]; then
-	echo "$SBUILDRPM_DIR does not exist, creating it..."
-	sudo install -d -m 2770 -o sbuild -g sbuild $SBUILDRPM_DIR
+  echo "$SBUILDRPM_DIR does not exist, creating it..."
+  sudo install -d -m 2770 -o sbuild -g sbuild $SBUILDRPM_DIR
 fi
 
 ############
@@ -67,20 +67,20 @@ fi
 while getopts "lkh" OPTIONS
 do
   case $OPTIONS in
-    l)
-		DO_RPMLINT=1
-		;;
-    k)
-	  KEEP_SESSION=1
-		;;
-    h)
-		usage
-	  exit 0
-		;;
-		*)
-		usage
-		exit 1
-		;;
+  l)
+    DO_RPMLINT=1
+  ;;
+  k)
+    KEEP_SESSION=1
+  ;;
+  h)
+    usage
+    exit 0
+  ;;
+  *)
+    usage
+    exit 1
+  ;;
   esac
 done
 shift $((OPTIND - 1))
@@ -98,7 +98,7 @@ VERSION=$(grep -e "^%define version" $SPEC_FILE | sed -e "s/^%define version[[:s
 RELEASE=$(grep -e "^%define release" $SPEC_FILE | sed -e "s/^%define release[[:space:]]//" )
 [ -n "$NAME" -a -n "$SOURCE0" -a -n "$VERSION" -a -n "$RELEASE" ] || die "Fail to fetch info from SPEC file."
 TARBALL=${SOURCE0/\%version/$VERSION}
-[ -r $TARBALLS_DIR/$TARBALL ] || die "Tarball $TARBALL not found."
+[ -r $TARBALLS_DIR/$TARBALL ] || die "Tarball $TARBALL not found (should be in $TARBALLS_DIR)."
 
 mkdir -p $SBUILDRPM_DIR/build
 SBUILDRPM_BUILD_DIR=$(mktemp -d --tmpdir=$SBUILDRPM_DIR/build -t $NAME-XXXXXX)
@@ -118,6 +118,7 @@ schroot -c $CHROOT_SESSION -r -d /build/$CHROOT_SESSION -- rpmbuild -bs SPECS/$N
 schroot -c $CHROOT_SESSION -r -d /build/$CHROOT_SESSION -u root -- yum-builddep -y SRPMS/oar-$VERSION-$RELEASE.src.rpm
 schroot -c $CHROOT_SESSION -r -d /build/$CHROOT_SESSION -- rpmbuild -ba SPECS/$NAME.spec
 [ -n "$DO_RPMLINT" ] && schroot -c $CHROOT_SESSION -r -d /build/$CHROOT_SESSION -- rpmlint RPMS/*.rpm
+mkdir -p $RPMBUILD_DIR/SRPMS/ $RPMBUILD_DIR/RPMS/
 cp -vf $SBUILDRPM_BUILD_DIR/SRPMS/* $RPMBUILD_DIR/SRPMS/
 cp -vf $SBUILDRPM_BUILD_DIR/RPMS/* $RPMBUILD_DIR/RPMS/
 cleanup
