Add the ability to the user to specify ssh key pair to connect between their nodes. Resolve the problem of a grid reservation with different OAR with different ssh keys.

diff --git a/Tools/oarsh/oarsh b/Tools/oarsh/oarsh
--- a/Tools/oarsh/oarsh
+++ b/Tools/oarsh/oarsh
@@ -59,5 +59,16 @@ then
     fi
 fi
 
+# Test if a specific ssh connection key is used
+SSH_KEY_FILE="/tmp/oar_runtime/$OAR_CPUSET.sshkey"
+if [ -r $SSH_KEY_FILE ]
+then
+    exec ssh -i $SSH_KEY_FILE "$@"
+    echo "[OARSH] Exec wih the key failed"
+    exit 5
+fi
+
 exec ssh -oSendEnv="OAR_CPUSET SUDO_USER" "$@"
+echo "[OARSH] Exec with environments failed"
+exit 6
 
