fix connexion when not using job key

diff --git a/Tools/oarsh/oarsh b/Tools/oarsh/oarsh
--- a/Tools/oarsh/oarsh
+++ b/Tools/oarsh/oarsh
@@ -68,14 +68,18 @@ fi
 # -2- try connection using a job key pushed by OAR for a job using the job key mechanism. 
 # (oarsh is run from one of the node of the job) 
 if [ -r /proc/self/cpuset ]; then
-    CPUSET=$(< /proc/self/cpuset)
-    if echo $CPUSET | grep -q "^/"$SUDO_USER"_"; then
-        JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/$CPUSET.jobkey"
+    OAR_CPUSET=$(< /proc/self/cpuset)
+    if echo $OAR_CPUSET | grep -q "^/"$SUDO_USER"_"; then
+        JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/$OAR_CPUSET.jobkey"
         if [ -r $JOB_KEY_FILE ]; then
             exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -i $JOB_KEY_FILE "$@"
             echo "oarsh: Failed to connect using the cpuset job key: $JOB_KEY_FILE"
             exit 3
         fi
+        export OAR_CPUSET
+        exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET SUDO_USER" "$@"
+        echo "oarsh: Failed to connect using cpuset environement"
+        exit 8
     fi
 fi
 
@@ -90,7 +94,7 @@ if [ -n "$OAR_JOB_ID" ]; then
         echo "oarsh: Cannot connect using job id from this host." 1>&2
         exit 5
     fi
-    export OAR_CPUSET=$($OARSH_OARSTAT_CMD -fj $OAR_JOB_ID | grep "^    cpuset_name = " | cut -d " " -f 7)
+    OAR_CPUSET=$($OARSH_OARSTAT_CMD -fj $OAR_JOB_ID | grep "^    cpuset_name = " | cut -d " " -f 7)
     if [ "$OAR_CPUSET" == "" ]; then
         echo "oarsh: Cannot retrieve the job cpuset name for job id: $OAR_JOB_ID" 1>&2
         exit 6
@@ -100,6 +104,7 @@ if [ -n "$OAR_JOB_ID" ]; then
             exit 7
         fi
     fi
+    export OAR_CPUSET
     exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET SUDO_USER" "$@"
     echo "oarsh: Failed to connect using cpuset environement"
     exit 8
diff --git a/Tools/oarsh/oarsh_shell b/Tools/oarsh/oarsh_shell
--- a/Tools/oarsh/oarsh_shell
+++ b/Tools/oarsh/oarsh_shell
@@ -18,7 +18,7 @@ function add_process_to_cpuset() {
     
     if ( ! $(sudo test -w $CPUSETFILE) )
     then
-        echo "[OARSH] Cannot find cpuset file : $CPUSETFILE" 1>&2
+        echo "OARSH: Cannot find cpuset file : $CPUSETFILE" 1>&2
         exit 1
     fi
     shift
@@ -34,8 +34,8 @@ if [ "$SUDO_USER" == "" ]
 then
     if [ "$SSH_CLIENT" != ""  ] && [ "$OAR_KEY" != "1" ]
     then
-        echo "[OARSH] The OAR_KEY environment variable is not defined and this seems to be a oar user connection." 1>&2
-        echo "[OARSH] See 'Important notes' part of the 'CPUSET installation' section of the OAR documentation." 1>&2
+        echo "OARSH: The OAR_KEY environment variable is not defined and this seems to be a oar user connection." 1>&2
+        echo "OARSH: See 'Important notes' part of the 'CPUSET installation' section of the OAR documentation." 1>&2
         exit 5
     fi
     # It must be oar
@@ -48,7 +48,7 @@ then
 else
     if [ "$OAR_CPUSET" == "" ]
     then
-        echo "[OARSH] OAR_CPUSET variable is empty; Is your sshd right configured with 'AcceptEnv OAR_CPUSET SUDO_USER' on all computing nodes?" 1>&2
+        echo "OARSH: OAR_CPUSET variable is empty; Is your sshd right configured with 'AcceptEnv OAR_CPUSET SUDO_USER' on all computing nodes?" 1>&2
         exit 3
         
     fi
@@ -77,7 +77,7 @@ else
         export SHELL=$(echo $PASSWD_LINE | cut -d : -f 7)
         if [ "$SHELL" == "" ]
         then
-            echo "[OARSH_SHELL] ERROR: No shell found for user $SUDO_USER." 1>&2
+            echo "OARSH: No shell found for user $SUDO_USER." 1>&2
             exit 4
         else
             export HOME=$(echo $PASSWD_LINE | cut -d : -f 6)
