version to test use OAR_CPUSET="undef" to notify that we are using unique UID but no cpuset

diff --git a/Tools/oarsh/oarsh b/Tools/oarsh/oarsh
--- a/Tools/oarsh/oarsh
+++ b/Tools/oarsh/oarsh
@@ -12,7 +12,7 @@
 OARSH_OARSTAT_CMD=
 OPENSSH_CMD=/usr/bin/ssh
 OARSH_OPENSSH_DEFAULT_OPTIONS="-oProxyCommand=none -oPermitLocalCommand=no"
-CPUSET_PATH="/oar"
+CPUSET_PATH=
 ###############################################################################
 
 source "$OARCONFFILE" || exit 2
@@ -75,20 +75,22 @@ if [ -r $TMP_JOB_KEY_FILE ]; then
     exit 4
 fi
 
-if [ -r /proc/self/cpuset ]; then
-    OAR_CPUSET=$(< /proc/self/cpuset)
-    if echo $OAR_CPUSET | grep -q "$CPUSET_PATH"; then
-        JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/${OAR_CPUSET##*/}.jobkey"
-        if [ -r $JOB_KEY_FILE ]; then
-            exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -i $JOB_KEY_FILE "$@"
-            echo "oarsh: Failed to connect using the cpuset job key: $JOB_KEY_FILE"
-            exit 4
+if [ "$CPUSET_PATH" != "" ]; then
+    if [ -r /proc/self/cpuset ]; then
+        OAR_CPUSET=$(< /proc/self/cpuset)
+        if echo $OAR_CPUSET | grep -q "$CPUSET_PATH"; then
+            JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/${OAR_CPUSET##*/}.jobkey"
+            if [ -r $JOB_KEY_FILE ]; then
+                exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -i $JOB_KEY_FILE "$@"
+                echo "oarsh: Failed to connect using the cpuset job key: $JOB_KEY_FILE"
+                exit 4
+            fi
+            export OAR_CPUSET
+            export OAR_JOB_USER=$SUDO_USER
+            exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET OAR_JOB_USER" "$@"
+            echo "oarsh: Failed to connect using cpuset environement"
+            exit 5
         fi
-        export OAR_CPUSET
-        export OAR_JOB_USER=$SUDO_USER
-        exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET OAR_JOB_USER" "$@"
-        echo "oarsh: Failed to connect using cpuset environement"
-        exit 5
     fi
 fi
 
@@ -108,13 +110,11 @@ if [ -n "$OAR_JOB_ID" ]; then
         echo "oarsh: Cannot retrieve the job cpuset name for job id: $OAR_JOB_ID" 1>&2
         exit 5
     else
-        if ! echo $OAR_CPUSET | grep -q "^"$SUDO_USER"_"; then
+        if [ "$OAR_CPUSET" != "$SUDO_USER"_"$OAR_JOB_ID" ]; then
             echo "oarsh: Permission denied, seems like job $OAR_JOB_ID is not yours." 1>&2
             exit 5
         fi
     fi
-    OAR_CPUSET="$CPUSET_PATH/$OAR_CPUSET"
-    export OAR_CPUSET
         
     # Check if we must use a tmp user id for this job
     TMP_OAR_JOB_USER=$($OARSH_OARSTAT_CMD -fj $OAR_JOB_ID | grep "^    job_user = " | cut -d " " -f 7)
@@ -123,7 +123,13 @@ if [ -n "$OAR_JOB_ID" ]; then
     else
         OAR_JOB_USER=$SUDO_USER
     fi
+    if [ "$CPUSET_PATH" != "" ]; then
+        OAR_CPUSET="$CPUSET_PATH/$OAR_CPUSET"
+    else
+        OAR_CPUSET="undef"
+    fi
     export OAR_JOB_USER
+    export OAR_CPUSET
 
     exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET OAR_JOB_USER" "$@"
     echo "oarsh: Failed to connect using cpuset environement"
diff --git a/Tools/oarsh/oarsh_shell b/Tools/oarsh/oarsh_shell
--- a/Tools/oarsh/oarsh_shell
+++ b/Tools/oarsh/oarsh_shell
@@ -12,7 +12,7 @@ OAR_SHELL_WRAPPER="/etc/oar/shell_user_wrapper.sh"
 # $2,$3,... = PIDs to add
 # Add PIDS into the cpuset $1
 function add_process_to_cpuset() {
-    [ "$DISABLE_CPUSET_MANAGEMENT" != "" ] && return
+    [ "$1" != "undef" ] && return
     ######################
     # CPUSET assignation #
     ###########################################################################
@@ -60,10 +60,13 @@ then
     if [ "$OAR_CPUSET" != "" ]
     then
         add_process_to_cpuset $OAR_CPUSET $$ $PPID || exit 2
-        sudo renice 0 $$ $PPID > /dev/null 2>&1
     fi
+    sudo renice 0 $$ $PPID > /dev/null 2>&1
     export SHELL=$DEFAULT_SHELL
+    
     exec $DEFAULT_SHELL "$@"
+    echo "oarsh: exec failed" 1>&2
+    exit 6
 else
     if [ "$OAR_CPUSET" == "" ]
     then
@@ -90,17 +93,28 @@ else
         then
             get_and_set_user_info $OAR_JOB_USER
             exec sudo -H -u $OAR_JOB_USER $OAR_SHELL_WRAPPER $SHELL
+            echo "oarsh: exec failed" 1>&2
+            exit 6
         else    
             exec sudo -i -u $OAR_JOB_USER
+            echo "oarsh: exec failed" 1>&2
+            exit 6
         fi
     else
         get_and_set_user_info $OAR_JOB_USER
         if [ -x "$OAR_SHELL_WRAPPER" ]
         then
             exec sudo -H -u $OAR_JOB_USER $OAR_SHELL_WRAPPER $SHELL "$@"
+            echo "oarsh: exec failed" 1>&2
+            exit 6
         else
             exec sudo -H -u $OAR_JOB_USER $SHELL "$@"
+            echo "oarsh: exec failed" 1>&2
+            exit 6
         fi
     fi
 fi
+
+echo "oarsh: Really bad error" 1>&2
+exit 7
 
